services:
  db:
    container_name: postgres
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tradio-backend
  redis:
    container_name: redis
    image: redis:8.0.2
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - tradio-backend
  localstack:
    container_name: localstack
    restart: always
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/data
    volumes:
      - ./localstack_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tradio-backend

volumes:
  postgres_data:
  redis_data:
  localstack:

networks:
  tradio-backend:
